sendwithus.template.*:
  type: config_entity
  label: 'Template config'
  mapping:
    id:
      type: string
      label: 'ID'
    key:
      type: string
      label: 'Key'
    module:
      type: string
      label: 'Module'
    uuid:
      type: string
